name: Publication

on:
  release:
    types: [released]

env:
  CARGO_TERM_COLOR: always

jobs:
  do_publication:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish
        env:
         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish
